### ISSUE TITLE
Unable to compile (libtommath dependencies)

### ISSUE THREAD

**Issue by clarkewd** [charlesnathansmith/wl_regkey#1]
This is such an interesting algorithm what a great writeup!

I tried to compile this code on VS2022 but am getting errors related to missing files from libtommath. 

For example, the `rsa.cpp` file has `#include "libtommath/tommath.h"` but that file does not exist inside the `libtommath` directory inside of the `rsa` folder.

I tried to download the `libtommath` at https://github.com/libtom/libtommath but I'm still getting compile errors. I've tried the main and dev branches and also the 1.2.0 tag.

Which version of libtommath are you using?

**Comment by charlesnathansmith** [comment]
Thanks for bringing it to my attention.  Somehow part of the libtommath library didn't initially upload properly.
I fixed the missing files and the repository builds as-is without external dependencies on VS2022 on my end now, but please verify it on yours when you have a chance.

Keep in mind that this can only build license files when you already have the secret keys and hashes required for a program.
(https://github.com/charlesnathansmith/whatlicense) is a work in progress aimed at extracting the keys from protected programs.  It currently only works for 32-bit protected programs but has been successful on the limited programs I've been able to get hold of to test it on.  There are plans to extend it to 64-bit protected programs. Their verification steps follow roughly the same blueprint, but there are still a lot of details to work out before it will work with those.

**Comment by clarkewd** [comment]
Yes! It builds for me now with no dependencies. Thanks so much for making the update!

And yes, I think I read that only the public key is embedded in a program so there is no way to generate a working license using this unless it is your program and you have access to the original private key. But the algorythm is very interesting so I wanted to see it at work after reading the paper.

I enjoyed reading your WL `tech_details.pdf` and this repo's `regkey_format.pdf` and would be very interested in reading another paper about divining the hashes from a protected program if you ever get to writing it.

**Comment by charlesnathansmith** [comment]
Alright, great to hear it's working now!

The ```tech_details.pdf``` paper is designed to follow the source for the extraction Pin tool one-to-one to demonstrate exactly what has to be done to bypass, extract, and calculate different parts of it.  Obviously I'm so deep into it that what's clear to me  in the walkthrough probably isn't to everyone else.

Whenever I have a chance to finish the 64-bit extractor, I'll probably try to make a more fleshed-out writeup covering both.

Glad you enjoyed it so far!
